# .github/workflows/render-md-mermaid.yml

name: Render Mermaid Diagrams

on:
  push:
    paths:
      - '**.md'

jobs:
  render-mermaid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # Updated to the latest version

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Render Mermaid diagrams from Markdown
        run: mmdc -i AWS.md -o AWS_diagram.png   # Render Mermaid diagrams into PNG format

      - name: Commit rendered diagrams
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatically rendered Mermaid diagrams"
          file_pattern: "*.png"
